[project]
name = "onert-micro"
version = "1.0.0"
maintainers = [
  { name="onert-micro-team", email="e.maltsev@samsung.com" },
]
description = "onert-micro: A lightweight neural network inference framework for microcontrollers"
readme = "README.md"
requires-python = ">=3.10"
license-files = [
  "LICENSE"
]

[project.urls]
"Homepage" = "https://github.com/onert-micro-team/onert-micro"
"Repository" = "https://github.com/onert-micro-team/onert-micro"
"Issues" = "https://github.com/onert-micro-team/onert-micro/issues"

[dependency-groups]
dev = [
  "pre-commit==4.4.0",
]

# This file does not describe packaging details for the library
